[package]
name = "audit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "audit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cuid2 = { workspace = true }
common = { path = "../common" }
