[package]
name = "dmp-audit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dmp-audit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }
rust_xlsxwriter = { workspace = true }
