import type { H3Event } from 'h3'
import type { Prisma } from '@prisma/client'
import { prisma } from '~/server/utils/prisma'

// Favorites and MANUAL playlists are per-user and private (userId set); GENRE/REGION playlists are
// shared/generated (userId null, regenerated by scripts/playlists). See CLAUDE.md Data Model.
// requirePermission already 401s when there's no session, so callers use this only after that check.
export const currentUserId = (event: H3Event): number => event.context.user!.id

// A playlist is visible to a user if they own it, or it's a shared generated one.
export const visiblePlaylistsWhere = (userId: number): Prisma.PlaylistWhereInput => ({
  OR: [{ userId }, { userId: null }],
})

// For write routes (create/delete tracks, delete playlist): 404 for anything not owned by this user
// - including a generated playlist (always userId null, never matches) or another user's playlist -
// never a 403 that would leak which slugs exist for someone else. The DB CHECK constraint
// (type = 'MANUAL') = (userId IS NOT NULL) means a row matching {slug, userId} is always MANUAL.
export const findOwnManualPlaylist = async (slug: string, userId: number) => {
  const playlist = await prisma.playlist.findFirst({ where: { slug, userId } })
  if (!playlist) {
    throw createError({ statusCode: 404, statusMessage: 'Playlist not found' })
  }
  return playlist
}
