[package]
name = "delete"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "delete"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
dotenvy = { workspace = true }
colored = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
chrono = { workspace = true }
