[package]
name = "index"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "index"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
sqlx = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
jwalk = { workspace = true }
rayon = { workspace = true }
lofty = { workspace = true }
image = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
colored = { workspace = true }
md-5 = { workspace = true }
dotenvy = { workspace = true }
slug = { workspace = true }
cuid2 = { workspace = true }
futures = { workspace = true }
