-- Favorites and MANUAL playlists become per-user and private (see CLAUDE.md Data Model). GENRE/
-- REGION playlists stay shared (userId NULL), generated by scripts/playlists.
--
-- No owner exists for current rows, so they are dropped rather than guessed at (confirmed with
-- user 2026-09-14). PlaylistTrack cascades away with its Playlist.

DELETE FROM "FavoriteRelease";
DELETE FROM "FavoriteTrack";
DELETE FROM "Playlist" WHERE "type" = 'MANUAL';

-- 1. FavoriteRelease: userId + composite unique replacing the old global-unique releaseId
DROP INDEX "FavoriteRelease_releaseId_key";
ALTER TABLE "FavoriteRelease" ADD COLUMN "userId" INTEGER NOT NULL;
CREATE UNIQUE INDEX "FavoriteRelease_userId_releaseId_key" ON "FavoriteRelease"("userId", "releaseId");
CREATE INDEX "FavoriteRelease_userId_idx" ON "FavoriteRelease"("userId");
ALTER TABLE "FavoriteRelease" ADD CONSTRAINT "FavoriteRelease_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 2. FavoriteTrack: same shape
DROP INDEX "FavoriteTrack_trackId_key";
ALTER TABLE "FavoriteTrack" ADD COLUMN "userId" INTEGER NOT NULL;
CREATE UNIQUE INDEX "FavoriteTrack_userId_trackId_key" ON "FavoriteTrack"("userId", "trackId");
CREATE INDEX "FavoriteTrack_userId_idx" ON "FavoriteTrack"("userId");
ALTER TABLE "FavoriteTrack" ADD CONSTRAINT "FavoriteTrack_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 3. Playlist: userId nullable (NULL = generated/shared). slug uniqueness splits into two rules
--    Prisma's declarative schema can't express on its own:
--      - per-owner: (userId, slug) composite unique (below, from @@unique in schema.prisma)
--      - among generated rows: a second, partial unique index, since Postgres treats NULL != NULL
--        in a composite unique and would otherwise let two generated playlists share a slug
--    CHECK ties type to ownership: MANUAL always has an owner, GENRE/REGION never do.
DROP INDEX "Playlist_slug_key";
ALTER TABLE "Playlist" ADD COLUMN "userId" INTEGER;
ALTER TABLE "Playlist" ADD CONSTRAINT "Playlist_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX "Playlist_userId_slug_key" ON "Playlist"("userId", "slug");
CREATE UNIQUE INDEX "Playlist_generated_slug_key" ON "Playlist"("slug") WHERE "userId" IS NULL;
CREATE INDEX "Playlist_userId_idx" ON "Playlist"("userId");
ALTER TABLE "Playlist" ADD CONSTRAINT "Playlist_manual_has_owner_check"
    CHECK (("type" = 'MANUAL') = ("userId" IS NOT NULL));

-- 4. VIEWER can now write its own favorites/playlists (writes only ever touch the caller's own rows)
INSERT INTO "RolePermission" ("role", "permission")
VALUES ('VIEWER', 'favorites.crud'), ('VIEWER', 'playlists.crud')
ON CONFLICT DO NOTHING;
